ObisConcept:
  includeFrontendAssets: true
  NeosGmaps:
    apiKey: ''
Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          ObisConcept.NeosGmaps:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        ObisConcept.NeosGmaps: true
